#!/bin/sh
set -e

# Note: we don't just use "apache2ctl" here because it itself is just a shell-script wrapper around apache2 which provides extra functionality like "apache2ctl start" for launching apache2 in the background.
# (also, when run as "apache2ctl <apache args>", it does not use "exec", which leaves an undesirable resident shell process)

: "${APACHE_CONFDIR:=/etc/apache2}"
: "${APACHE_ENVVARS:=$APACHE_CONFDIR/envvars}"
if test -f "$APACHE_ENVVARS"; then
        . "$APACHE_ENVVARS"
fi

# Apache gets grumpy about PID files pre-existing
: "${APACHE_RUN_DIR:=/var/run/apache2}"
: "${APACHE_PID_FILE:=$APACHE_RUN_DIR/apache2.pid}"
rm -f "$APACHE_PID_FILE"

# create missing directories
# (especially APACHE_RUN_DIR, APACHE_LOCK_DIR, and APACHE_LOG_DIR)
if [ -n "$APACHE_RUN_DIR" ] && [ -d "$(dirname "$APACHE_RUN_DIR")" ]; then
    mkdir -p "$APACHE_RUN_DIR"
fi
if [ -n "$APACHE_LOCK_DIR" ] && [ -d "$(dirname "$APACHE_LOCK_DIR")" ]; then
    mkdir -p "$APACHE_LOCK_DIR"
fi
if [ -n "$APACHE_LOG_DIR" ] && [ -d "$(dirname "$APACHE_LOG_DIR")" ]; then
    mkdir -p "$APACHE_LOG_DIR"
fi

exec apache2 -DFOREGROUND "$@"
