version: "3.3"

services:

  omekas:
    depends_on:
      - omekas_db
    image:  docker.io/giocomai/omeka-s-docker:v4.1.1.production
    container_name: omekas
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_HOST: omekas_db
    volumes:
      - omekas:/var/www/html/volume:Z

  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    volumes:
      - omeka_db:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME

volumes:
  omeka_db:
  omekas:
