version: "3.3"

services:

  omekas:
    build: .
    depends_on:
      - omekas_db
    image:  docker.io/giocomai/omeka-s-docker:v4.1.1.production
    container_name: omekas
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_HOST: omekas_db
      APPLICATION_ENV: development
      OMEKA_THEMES: https://github.com/omeka-s-themes/default/releases/download/v1.9.1/theme-default-v1.9.1.zip
      OMEKA_MODULES: |
        https://github.com/Daniel-KM/Omeka-S-module-Common/releases/download/3.4.66/Common-3.4.66.zip      
        https://github.com/Daniel-KM/Omeka-S-module-EasyAdmin/releases/download/3.4.29/EasyAdmin-3.4.29.zip
        https://github.com/Daniel-KM/Omeka-S-module-Adminer/releases/download/3.4.5-4.8.4/Adminer-3.4.5-4.8.4.zip
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 300
      OMEKA_ADMIN_EMAIL: admin@example.com
      OMEKA_ADMIN_NAME: "Site Administrator"
      OMEKA_ADMIN_PASSWORD: supersecret
      OMEKA_SITE_TITLE: "My Omeka Site"
    volumes:
      - omekas:/var/www/html/volume:Z

  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    volumes:
      - omeka_db:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME

volumes:
  omeka_db:
  omekas:
