version: "3.3"

services:

  omekas:
    build: .
    depends_on:
      - omekas_db
    image:  docker.io/giocomai/omeka-s-docker:v4.1.1.production
    container_name: omekas
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_HOST: omekas_db
      APPLICATION_ENV: development
      OMEKA_THEMES: https://github.com/omeka-s-themes/default
      OMEKA_MODULES: |
        https://github.com/Daniel-KM/Omeka-S-module-Common
        https://github.com/Daniel-KM/Omeka-S-module-EasyAdmin
        https://github.com/Daniel-KM/Omeka-S-module-Adminer
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 300

    volumes:
      - omekas:/var/www/html/volume:Z

  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    volumes:
      - omeka_db:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME

volumes:
  omeka_db:
  omekas:
